version: 0.2
phases:
  pre_build:
    commands:
      - echo BEGIN Logging in to Amazon ECR.....
      - echo $AWS_DEFAULT_REGION
      - API_REPOSITORY_URI=402846102310.dkr.ecr.us-east-1.amazonaws.com/analytics
      - AWS_DEFAULT_REGION=us-east-1
      - aws ecr get-login-password | docker login --username AWS --password-stdin $API_REPOSITORY_URI
  build:
    commands:
      - cd analytics
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo Build started on `date`
      - echo $IMAGE_TAG
      - echo Building the Docker image...
      - docker build -t $API_REPOSITORY_URI:latest -f Dockerfile .
      - docker tag $API_REPOSITORY_URI:latest $API_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $API_REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  name: $BUILD_VERSION
